# Generated by Django 3.1.2 on 2020-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=100, verbose_name='Name of task')),
                ('description_task', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
